/*****************************************************************************
 * University of Southern Denmark
 * Pan Tilt Project
 *
 * MODULENAME.: menu
 *****************************************************************************/

//							MENU PROTOTYPE
//	SETUP(-name of menu-)
//		TOP(" -top 16 chars- ")			BOTTOM(" -bottom 16 chars- ")
//		NEXT( -name of menu- )			PREV( -name of menu- )
//		ENTER( -name of menu- )			TYPE( -menu type- )
//	INIT_FIELDS
//		FIELD(number,x,y,size)			PARAM(field, -name of parameter- ) ACD(field)
//		FIELD(number,x,y,size)			PARAM(field, -name of parameter- ) DREH(field)
//		FIELD(number,x,y,size)			BLINK(field)

/***************************** Include files *******************************/
#include "menu.h"

/*****************************   Functions   *******************************/
void init_menus(void)
{
	menu_t *dummy;
	struct text_struct menu_texts[NUMBER_OF_MENUS];
	INT8U i;
	menu_handler(FIRST_RUN_M);

	MENU_TEXT(	FUNCTIONS_M,			"FUNC            ",
										"REG  FREE   AUTO")
		SETUP(FUNCTIONS_M_REG)			TEXT(FUNCTIONS_M)			TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(FUNCTIONS_M_FREE)			PREV(INFO_M_ERROR)			ENTER(FUNC_REG_M)
		FIELD(0,0,1,3)					BLINK(0)
		SETUP(FUNCTIONS_M_FREE)			TEXT(FUNCTIONS_M)			TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(FUNCTIONS_M_AUTO)			PREV(FUNCTIONS_M_REG)		ENTER(FUNC_FREE_M)
		FIELD(0,5,1,4)					BLINK(0)
		SETUP(FUNCTIONS_M_AUTO)			TEXT(FUNCTIONS_M)			TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(SETTINGS_M_REG)			PREV(FUNCTIONS_M_FREE)		ENTER(FUNC_AUTO_M)
		FIELD(0,12,1,4)					BLINK(0)

	MENU_TEXT(	SETTINGS_M,				"      SET       ",
										"REG   POS       ")
		SETUP(SETTINGS_M_REG)			TEXT(SETTINGS_M)			TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(SETTINGS_M_POS)			PREV(FUNCTIONS_M_AUTO)		ENTER(SET_REG_M)
		FIELD(0,0,1,3)					BLINK(0)
		SETUP(SETTINGS_M_POS)			TEXT(SETTINGS_M)			TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(INFO_M_POS)				PREV(SETTINGS_M_REG)		ENTER(SET_POS_M)
		FIELD(0,6,1,3)					BLINK(0)

	MENU_TEXT(	INFO_M,					"            INFO",
										"POS   ERROR     ")
		SETUP(INFO_M_POS)				TEXT(INFO_M)				TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(INFO_M_ERROR)				PREV(SETTINGS_M_POS)		ENTER(INFO_POS_M)
		FIELD(0,0,1,3)					BLINK(0)
		SETUP(INFO_M_ERROR)				TEXT(INFO_M)				TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(FUNCTIONS_M_REG)			PREV(INFO_M_POS)			ENTER(INFO_ERROR_M)
		FIELD(0,6,1,5)					BLINK(0)

	MENU_TEXT(	NOT_IMPLEMENTED,		"THIS FEATURE IS ",
										"NOT IMPLEMENTED ")
		SETUP(NOT_IMPLEMENTED)			TEXT(NOT_IMPLEMENTED)		TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(SYSTEM_START_MENU)			PREV(SYSTEM_START_MENU)		ENTER(SYSTEM_START_MENU)

	MENU_TEXT(	FUNC_FREE_M,			"< FUNC-FREE  STO",
										"P:      T:      ")
		SETUP(FUNC_FREE_M)				TEXT(FUNC_FREE_M)			TYPE(IS_MENU,NOT_INPUT,IS_CALL)
		NEXT(FUNC_FREE_STO_M)			PREV(FUNC_FREE_STO_M)		ENTER(FUNC_FREE_RET_CALL_M)
		FUNCTION(enter_freemode)
		FIELD(0,2,1,6)					PARAM(0,PAN_CURRENT_P)
		FIELD(1,10,1,6)					PARAM(1,TILT_CURRENT_P)
		FIELD(2,0,0,1)					BLINK(2)
		SETUP(FUNC_FREE_STO_M)			TEXT(FUNC_FREE_M)			TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(FUNC_FREE_RET_M)			PREV(FUNC_FREE_RET_M)		ENTER(FUNC_FREE_M_STO)
		FIELD(0,2,1,6)					PARAM(0,PAN_CURRENT_P)
		FIELD(1,10,1,6)					PARAM(1,TILT_CURRENT_P)
		FIELD(2,13,0,3)					BLINK(2)
		SETUP(FUNC_FREE_RET_M)			TEXT(FUNC_FREE_M)			TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(FUNC_FREE_STO_M)			PREV(FUNC_FREE_STO_M)		ENTER(FUNC_FREE_RET_CALL_M)
		FIELD(0,2,1,6)					PARAM(0,PAN_CURRENT_P)
		FIELD(1,10,1,6)					PARAM(1,TILT_CURRENT_P)
		FIELD(2,0,0,1)					BLINK(2)
		SETUP(FUNC_FREE_RET_CALL_M)		TEXT(FUNCTIONS_M)			TYPE(IS_MENU,NOT_INPUT,IS_CALL)
		NEXT(FUNCTIONS_M_AUTO)			PREV(FUNCTIONS_M_REG)		ENTER(FUNC_FREE_M)
		FUNCTION(exit_freemode)
		FIELD(0,5,1,4)					BLINK(0)

	MENU_TEXT(	FUNC_FREE_M_STO,		"< FUNC-FREE-STO ",
										"STORE AT: PO.   ")
		SETUP(FUNC_FREE_M_STO)			TEXT(FUNC_FREE_M_STO)		TYPE(NOT_MENU,IS_INPUT,NOT_CALL)
		NEXT(FUNC_REG_ON_M)				PREV(FUNC_REG_ON_M)			ENTER(FUNC_FREE_SAVED_M)
		FIELD(0,0,0,1)					BLINK(0)
		FIELD(1,13,1,1)					PARAM(1,SAVE_POS_P)			NUMPAD(1)

		SETUP(FUNC_FREE_SAVED_M)		TEXT(FUNC_FREE_M)			TYPE(IS_MENU,NOT_INPUT,IS_CALL)
		NEXT(FUNC_FREE_RET_M)			PREV(FUNC_FREE_RET_M)		ENTER(FUNC_FREE_M_STO)
		FUNCTION(save_position)
		FIELD(0,2,1,6)					PARAM(0,PAN_CURRENT_P)
		FIELD(1,10,1,6)					PARAM(1,TILT_CURRENT_P)
		FIELD(2,13,0,3)					BLINK(2)

	MENU_TEXT(	FUNC_REG_M,				"< FUNC-REG      ",
										"REGULATOR: OFF  ")
		SETUP(FUNC_REG_M)				TEXT(FUNC_REG_M)			TYPE(IS_MENU,NOT_INPUT,IS_CALL)
		NEXT(FUNC_REG_ON_M)				PREV(FUNC_REG_ON_M)			ENTER(FUNCTIONS_M_REG)
		FUNCTION(deactivate_regulator)
		FIELD(0,0,0,1)					BLINK(0)

	MENU_TEXT(	FUNC_REG_ON_M,			"< FUNC-REG      ",
										"REGULATOR: ON   ")
		SETUP(FUNC_REG_ON_M)			TEXT(FUNC_REG_ON_M)			TYPE(IS_MENU,NOT_INPUT,IS_CALL)
		NEXT(FUNC_REG_M)				PREV(FUNC_REG_M)			ENTER(FUNCTIONS_M_REG)
		FUNCTION(activate_regulator)
		FIELD(0,0,0,1)					BLINK(0)

	MENU_TEXT(	FUNC_AUTO_M,			"< FUNC-AUTO  OFF",
										"NEXT POS: PO.   ")
		SETUP(FUNC_AUTO_M)				TEXT(FUNC_AUTO_M)			TYPE(IS_MENU,NOT_INPUT,IS_CALL)
		NEXT(FUNC_AUTO_ON_M)			PREV(FUNC_AUTO_ON_M)		ENTER(FUNCTIONS_M_AUTO)
		FUNCTION(deactivate_automode)
		FIELD(0,0,0,1)					BLINK(0)
		FIELD(1,13,1,1)					PARAM(1,NEXT_POS_P)

	MENU_TEXT(	FUNC_AUTO_ON_M,			"< FUNC-AUTO   ON",
										"NEXT POS: PO.   ")
		SETUP(FUNC_AUTO_ON_M)			TEXT(FUNC_AUTO_ON_M)		TYPE(IS_MENU,NOT_INPUT,IS_CALL)
		NEXT(FUNC_AUTO_M)				PREV(FUNC_AUTO_M)			ENTER(FUNCTIONS_M_AUTO)
		FUNCTION(activate_automode)
		FIELD(0,0,0,1)					BLINK(0)
		FIELD(1,13,1,1)					PARAM(1,NEXT_POS_P)

	MENU_TEXT(	SET_REG_M,				"< SET-REG       ",
										"TYPE  PARAMETERS")
		SETUP(SET_REG_M)				TEXT(SET_REG_M)				TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(SET_REG_TYPE_M)			PREV(SET_REG_PARAMETERS_M)	ENTER(FUNCTIONS_M_AUTO)
		FIELD(0,0,0,1)					BLINK(0)
		SETUP(SET_REG_TYPE_M)			TEXT(SET_REG_M)				TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(SET_REG_PARAMETERS_M)		PREV(SET_REG_M)				ENTER(SET_REG_TYPE_PID_M)
		FIELD(0,0,1,4)					BLINK(0)
		SETUP(SET_REG_PARAMETERS_M)		TEXT(SET_REG_M)				TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(SET_REG_M)					PREV(SET_REG_TYPE_M)		ENTER(SET_REG_PARAM_M)
		FIELD(0,6,1,10)					BLINK(0)

	MENU_TEXT(	SET_REG_TYPE_PID_M,		"< SET-REG-TYPE  ",
										"  CLASSIC PID   ")
		SETUP(SET_REG_TYPE_PID_M)		TEXT(SET_REG_TYPE_PID_M)	TYPE(IS_MENU,NOT_INPUT,IS_CALL)
		NEXT(SET_REG_TYPE_SS_M)			PREV(SET_REG_TYPE_SS_M)		ENTER(SET_REG_M)
		FUNCTION(activate_pid)
		FIELD(0,0,0,1)					BLINK(0)

	MENU_TEXT(	SET_REG_TYPE_SS_M,		"< SET-REG-TYPE  ",
										"  STATE-SPACE   ")
		SETUP(SET_REG_TYPE_SS_M)		TEXT(SET_REG_TYPE_SS_M)		TYPE(IS_MENU,NOT_INPUT,IS_CALL)
		NEXT(SET_REG_TYPE_PID_M)		PREV(SET_REG_TYPE_PID_M)	ENTER(SET_REG_M)
		FUNCTION(activate_ss)
		FIELD(0,0,0,1)					BLINK(0)

	MENU_TEXT(	SET_REG_PARAM_M,		"< SET-REG-PARAM ",
										"                ")
		SETUP(SET_REG_PARAM_M)			TEXT(SET_REG_PARAM_M)	TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(SET_REG_PARAM_M)			PREV(SET_REG_PARAM_M)	ENTER(SET_REG_M)
		FIELD(0,0,0,1)					BLINK(0)

	MENU_TEXT(	SET_POS_M,				"< SET-POS       ",
										"P:      T:      ")
		SETUP(SET_POS_M)				TEXT(SET_POS_M)				TYPE(NOT_MENU,IS_INPUT,NOT_CALL)
		NEXT(SET_POS_M)					PREV(SET_POS_M)				ENTER(SETTINGS_M_POS)
		FIELD(0,2,1,6)					PARAM(0,PAN_SETPOINT_P)		ADC(0)
		FIELD(1,10,1,6)					PARAM(1,TILT_SETPOINT_P)	DREH(1)
		FIELD(2,0,0,1)					BLINK(2)

	MENU_TEXT(	INFO_POS_M,				"< INFO-POS      ",
										"P:      T:      ")
		SETUP(INFO_POS_M)				TEXT(INFO_POS_M)			TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(INFO_POS_M)				PREV(INFO_POS_M)			ENTER(INFO_M_POS)
		FIELD(0,2,1,6)					PARAM(0,PAN_CURRENT_P)
		FIELD(1,10,1,6)					PARAM(1,TILT_CURRENT_P)
		FIELD(2,0,0,1)					BLINK(2)

	MENU_TEXT(	INFO_ERROR_M,			"< INFO-ERROR    ",
										"P:      T:      ")
		SETUP(INFO_ERROR_M)				TEXT(INFO_ERROR_M)			TYPE(IS_MENU,NOT_INPUT,NOT_CALL)
		NEXT(INFO_ERROR_M)				PREV(INFO_ERROR_M)			ENTER(INFO_M_ERROR)
		FIELD(0,2,1,6)					PARAM(0,PAN_ERROR_P)
		FIELD(1,10,1,6)					PARAM(1,TILT_ERROR_P)
		FIELD(2,0,0,1)					BLINK(2)
}
